name: dart_pgmq
description: A dart client for Postgres Message Queue (PGMQ).
version: 1.0.0
repository: https://github.com/Ofceab-Studio/dart_pgmq
issue_tracker: https://github.com/Ofceab-Studio/dart_pgmq/issues
topics: [postgresql, message-queue, pgmq]

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  pausable_timer: ^3.1.0+3
  postgres: ^3.4.4
  dotenv: ^4.2.0
  # path: ^1.8.0

dev_dependencies:
  auto_exporter: ^3.3.1
  build_runner: ^2.4.9
  lints: ^2.1.0
  test: ^1.24.0

scripts:
  export: 'dart run build_runner build && mv lib/exports.dart lib/dart_pgmq.dart'
