name: dart_pgmq
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  postgres: ^3.2.1
  # path: ^1.8.0

dev_dependencies:
  auto_exporter: ^3.3.1
  build_runner: ^2.4.9
  lints: ^2.1.0
  test: ^1.24.0

scripts:
  export: 'dart run build_runner build && mv lib/exports.dart lib/dart_pgmq.dart'
